version: '3.8'

name: grocery-mssql

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Password!"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    user: root
    restart: on-failure
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password!", "-Q", "SELECT 1 || exit 1"]
      start_period: 15s
      start_interval: 10s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - .volumes/mssql-data:/var/opt/mssql/data
      - .volumes/mssql-backup:/var/opt/mssql/backup
      - .volumes/mssql-logs:/var/opt/mssql/log
      - .volumes/mssql-secrets:/var/opt/mssql/secrets